version: '3.8'

services:
  frontend:
    build:
      context: ./auction_front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./auction_front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./django_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./django_api:/app

networks:
  default:
    name: auction_network