name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and start containers
        run: docker-compose up --build -d

      - name: Wait for services to be healthy
        run: |
          docker-compose ps
          docker-compose exec -T <service_name> /bin/sh -c "until curl -s http://localhost:<port>; do sleep 5; done"

      - name: Run tests
        run: docker-compose exec -T <service_name> /bin/sh -c "pytest"

      - name: Tear down Docker Compose
        run: docker-compose down
