name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and start containers
        run: docker-compose up --build -d

      - name: Wait for backend service to be healthy
        run: |
          docker-compose ps
          docker-compose exec -T backend /bin/sh -c "until curl -s http://localhost:8000; do sleep 5; done"

      - name: Wait for frontend service to be healthy
        run: |
          docker-compose ps
          docker-compose exec -T frontend /bin/sh -c "until curl -s http://localhost:5173; do sleep 5; done"

      - name: Tear down Docker Compose
        run: docker-compose down
